import os
from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()

class LLMService:

    def __init__(self):
        api_key = os.getenv("GOOGLE_API_KEY")

        if not api_key:
            raise ValueError("❌ GOOGLE_API_KEY not found in .env")

        genai.configure(api_key=api_key)

    def generate_response(self, context, question):

        print(" Calling LLM...")

        try:
            # MODEL
            model = genai.GenerativeModel("gemini-3-flash-preview")

            prompt = f"""
            Answer ONLY from the context below.
            If the answer is not present, say "I don't know".

            Context:
            {context}

            Question:
            {question}
            """

            response = model.generate_content(prompt)

            if not response or not response.text:
                return " No response generated by LLM"

            return response.text.strip()

        except Exception as e:
            print(" LLM ERROR:", e)
            return " Error while generating response"
